### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by tanu611063** [tanu611063/chat-space#8]
IPアドレス
http://54.249.158.224/

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**ビューの崩れ**
<img width="1439" alt="ChatSpace" src="https://user-images.githubusercontent.com/44963290/83593180-0e7ded80-a597-11ea-9acb-25346ab4dd15.png">








参考カリキュラム:https://master.tech-camp.in/curriculums/3944

<img width="867" alt="ヘッダー" src="https://user-images.githubusercontent.com/44963290/77241139-85127c80-6c31-11ea-8f1d-da109523e77c.png">

<img width="862" alt="メッセージお手本" src="https://user-images.githubusercontent.com/44963290/83593203-1b9adc80-a597-11ea-963d-2fa970a0aef0.png">

<img width="865" alt="メッセージ記入欄" src="https://user-images.githubusercontent.com/44963290/83593214-2190bd80-a597-11ea-9041-24c6b76ce6a3.png">



修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by tanu611063** [comment]
上記３点修正完了致しました。
ご確認お願い致します。

**Comment by naru6117** [comment]
再度ご提出ありがとうございます！
挙動確認させて頂いたところ、
①「Member」の表示、②投稿フォームの10pxの余白についてはしっかり修正が出来ていました！
また、引き続き以下の不備が見受けられましたので修正をお願いします！

### [修正箇所]
**①非同期通信でメッセージが表示されるようにしましょう
②送信したメッセージの表示が、カリキュラムの指定通り表示されるようにしましょう**

②に関しては、現在下記の写真のような表示になっています。
![スクリーンショット 2020-06-03 15 33 28](https://user-images.githubusercontent.com/49669977/83603797-041c1d80-a5b0-11ea-9c7d-a072dd05bfaf.png)


修正が完了次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by tanu611063** [comment]
上記２点、再度修正完了致しました。
ご確認お願い致します。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、非同期通信については修正が確認できましたが、カリキュラムの規定どおりに、メッセージとメッセージの間が空いていませんでした。
また新たに以下の不備が見受けられましたので修正をお願いします。
あと少しです！

### [修正箇所]
**①自動更新にてメッセージが受信できない
　→自動更新がきちんとできるようにしましょう
②Sendボタンを2回押して、アラートが出現した後にメッセージが送信できない
　→リロードしなくてもメッセージが送れるようにしましょう
③「Log in」「Create Account」「Edit Account」の文字色を、カリキュラムの指定通りにしましょう
④送信したメッセージがカリキュラムの指定通りに表示されるようにしましょう
　↓現在の写真です**
<img width="329" alt="スクリーンショット 2020-06-03 16 11 28" src="https://user-images.githubusercontent.com/49669977/83606628-e7361900-a5b4-11ea-974a-c1edfcbb1696.png">

修正が完了次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by tanu611063** [comment]
上記４点修正完了致しました。
ご確認お願い致します。

**Comment by keisukekodama** [comment]
修正ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

※今後実装に関する質問がありましたら、メンターに確認をお願いします！
